### PR TITLE
added body.attributes in loginNewPasswordRequired.js

### PR DESCRIPTION
**Pull request by Varshney21**
Whenever its required to set some additional attributes along with the newPassword for an account which is initially created by the admin. The function does not read those attributes due to which they are not added for that account in the userpool. So, to solve this issue the following change has been made.

### CODE REVIEW

**Comment by frsechet** [comment]
Hi @Varshney21, I won't have time to review until at least this weekend (or maybe the one after) but I will check it out then. Thanks for the PR!

**Review by frsechet — DISMISSED** [review]
OK, makes sense, especially when there are required attributes involved.

**Comment by frsechet** [comment]
@Varshney21 can I ask you to resolve the conflicts before I merge? I made a large refactoring this morning, the change is extremely simple for you here:
- rebase on master
- make the same change in the file `src/methods/loginNewPasswordRequired.js`
- commit & push
- profit 😄

**Comment by Varshney21** [comment]
@frsechet Done.
Please look and let me know if anything else is required.

**Comment by frsechet** [comment]
Looks like you are still adding the src/loginNewPasswordRequired.js, instead of modifying src/methods/loginNewPasswordRequired.js.

If easier than cleaning up this merge, you can also close this one and reopen with just your modification!

**Comment by Varshney21** [comment]
@frsechet I have made the modifications in src/methods/loginNewPasswordRequired.js and deleted src/loginNewPasswordRequired.js.
Please look now.

**Comment by frsechet** [comment]
Thanks @Varshney21, published under 0.2.1. Cheers!

**Pull request merged**
