### PR TITLE
Add attribute confirmation/verification

### PR DESCRIPTION
**Pull request by sallar**
Hi, 

Some attributes such as email need verification when they're updated. This PR adds that. 

Thanks!

### CODE REVIEW

**Review by frsechet — APPROVED** [review]

**Comment by sallar** [comment]
@frsechet this was quick 😂 thanks! could you release too please?

**Comment by frsechet** [comment]
Already on it ;-) give me a sec

**Comment by frsechet** [comment]
Published under 0.2.3. Thanks for the PR!

**Comment by sallar** [comment]
Thanks! Already installed :) Awesome.

**Pull request merged**
